version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q5q0p8i1
  build: 
    commands:
      - docker build -t estrenazcel -f ./Dockerfile .
      - docker tag estrenazcel:latest public.ecr.aws/q5q0p8i1/estrenazcel:latest
      - docker push public.ecr.aws/q5q0p8i1/estrenazcel:latest
  post_build:
    commands:
      - echo final
      - aws ecs update-service --cluster clients --service estrenazcel --force-new-deployment