version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u5t1d9m6
  build: 
    commands:
      - docker build -t micros -f ./Dockerfile .
      - docker tag micros:latest public.ecr.aws/u5t1d9m6/micros:latest
  post_build:
    commands:
      - docker push public.ecr.aws/u5t1d9m6/micros:latest