services:
  estrenazcelbackend:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      - mariadb
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: postgres
        POSTGRES_DB: gpt
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  mariadb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gpt
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql